apiVersion: sfcn.cisco.com/v1
kind: VPC
metadata:
  name: invalid-vpc
  namespace: some-invalid-namespace
  annotations:
    "sfcn.cisco.com/spoof": "true"
spec:
  account: "329599101318"
  region: us-east-1
  defaultCidr: 172.16.0.0/16
  maxAZs: 2
  tags:
    env: dev
